#!/bin/bash
wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.asc.gpg
sudo mv microsoft.asc.gpg /etc/apt/trusted.gpg.d/
wget -q https://packages.microsoft.com/config/debian/9/prod.list
sudo mv prod.list /etc/apt/sources.list.d/microsoft-prod.list
sudo chown root:root /etc/apt/trusted.gpg.d/microsoft.asc.gpg
sudo chown root:root /etc/apt/sources.list.d/microsoft-prod.list

sudo add-apt-repository ppa:nilarimogard/webupd8

sudo apt-get update
sudo apt-get -y install meld gdb tree vsftpd ftp gnuplot-x11 gcc okular vscode g++ gfortran gnuplot python python3 octave git ssh vim mpich python-pip aria2 python3-pip llvm clang clang-4.0 nvidia-smi nvidia-cuda-dev nvidia-cuda-toolkit nvidia-nsight nvidia-visual-profiler engauge-digitizer flac lame ffmpeg shntool golang klatexformula gnash inkscape gimp deepin-nvidia-prime ngrok-client ngrok-server
sudo apt-get install prime-indicator dotnet-sdk-2.2
pip install -i https://pypi.tuna.tsinghua.edu.cn/simple/ sympy vtk scipy scikit-learn numpy matplotlib dataframe mayavi tensorflow pandas
pip3 install -i https://pypi.tuna.tsinghua.edu.cn/simple/ sympy vtk scipy scikit-learn numpy matplotlib dataframe mayavi tensorflow pandas pyqt

#starUML gimp 微信 TIM 百度网盘 迅雷
#ssh-key -t rsa -C "coiggahou@foxmail.com"
#ssh -T git@github.com

